---
- name: Installation des paquets nécessaires à l'installation de Unoserver
  apt:
    pkg:
      - libreoffice
      - python3-pip
- name: Installation de Unoserver (en local depuis ce rôle) pour la conversion des fichiers Office en PDF
  pip:
    name: "file://{{ role_path }}/files/unoserver-2.0-py3-none-any.whl"
    executable: pip3
    extra_args: --break-system-packages
